// Shapes of the rows in data/*.json (generated by the repo's Python extractors).
// We read these artifacts directly — no SQLite dependency.

export type Kind = "Virtue" | "Flaw";
export type Size = "Minor" | "Major" | "Free" | "Major or Minor";

export interface VirtueFlawRow {
  name: string;
  kind: Kind;
  size: Size;
  category: string;
  categories: string[];
  tainted: boolean;
  cost_raw: string;
  description: string;
  source_file: string;
  source_line: number;
}

export type AbilityType = "General" | "Academic" | "Arcane" | "Martial" | "Supernatural" | null;

export interface AbilityRow {
  name: string;
  type: AbilityType;
  restricted: boolean;
  specialties: string;
  description: string;
  source_file: string;
  source_line: number;
}

export interface SpellRow {
  name: string;
  technique: string;
  form: string;
  tech_abbr: string;
  form_abbr: string;
  level: number | null;
  is_general: boolean;
  is_ritual: boolean;
  range: string;
  duration: string;
  target: string;
  requisites: string[];
  damage: number | null;
  design_raw: string | null;
  description: string;
  source_file: string;
  source_line: number;
}
